name: gptoolsStan R package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  cmdstanVersion: "2.31.0"

jobs:
  build:
    name: Build
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: "actions/checkout@v2"
      - name: Install Windows dependencies.
        run: choco install pandoc
        if: matrix.runner == 'windows-latest'
      - uses: "r-lib/actions/setup-r@v2"
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            cmdstanr=url::https://mc-stan.org/r-packages/src/contrib/cmdstanr_0.7.0.tar.gz
          needs: check
      - uses: r-lib/actions/check-r-package@v2
